CREATE TABLE users (
    id BIGSERIAL PRIMARY KEY,
    display_name VARCHAR(100) NOT NULL,
    email VARCHAR(255) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

ALTER TABLE campaigns
ADD COLUMN user_id BIGINT;

ALTER TABLE campaigns
ADD CONSTRAINT fk_campaign_user
FOREIGN KEY (user_id)
REFERENCES users(id);